### ISSUE TITLE
GoogleDrive problem

### ISSUE THREAD

**Issue by AlexVolkov1987** [tarampampam/static#3]
clients6.google.com активно используется google drive для загрузки содержимого страниц сервиса, ее попадание в список приводит фактически к отказу работы. 
![clients6 google com added](https://user-images.githubusercontent.com/2890623/59566767-58f81880-906d-11e9-8cd9-d916b18ad8a4.jpg)
![clients6 google com deleted](https://user-images.githubusercontent.com/2890623/59566768-58f81880-906d-11e9-971c-092c16464180.jpg)

**Comment by tarampampam** [comment]
b845c4350a69c56aff49fe184f3bdea0ef9aa54e
